export const insuranceList = [
  { label: "Statefarm", value: "Statefarm" },
  { label: "Geico", value: "Geico" },
  { label: "Progressive", value: "Progressive" },
  { label: "Allstate", value: "Allstate" },
  { label: "Esurance", value: "Esurance" },
  { label: "National General", value: "National General" },
  { label: "USAA", value: "USAA" },
  { label: "Liberty Mutual", value: "Liberty Mutual" },
  { label: "Safeco", value: "Safeco" },
  { label: "Farmers", value: "Farmers" },
  { label: "Nationwide", value: "Nationwide" },
  { label: "Erie Insurance", value: "Erie Insurance" },
  { label: "Kemper", value: "Kemper" },
  { label: "Mercury Insurance", value: "Mercury Insurance" },
  { label: "Metlife", value: "Metlife" },
  { label: "The Hartford", value: "The Hartford" },
  { label: "Amica", value: "Amica" },
  { label: "Hanover", value: "Hanover" },
  { label: "NJM", value: "NJM" },
  { label: "Sentry", value: "Sentry" },
  { label: "Alfa", value: "Alfa" },
  { label: "Chubb", value: "Chubb" },
  { label: "Plymouth Rock", value: "Plymouth Rock" },
  { label: "American National", value: "American National" },
  { label: "Travelers", value: "Travelers" },
  { label: "American Transit", value: "American Transit" },
  { label: "Countrywide", value: "Countrywide" },
  { label: "Seneca", value: "Seneca" },
  { label: "Hereford", value: "Hereford" },
  { label: "Star", value: "Star" },
  { label: "Utica", value: "Utica" },
  { label: "Zurich", value: "Zurich" },
  { label: "Other", value: "Other" }
]
