/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_dynamodb_all_tables_region": "us-east-1",
  "aws_dynamodb_table_schemas": [
      {
          "tableName": "coreDynamo-dev",
          "region": "us-east-1"
      }
  ],
  "aws_cloud_logic_custom": [
      {
          "name": "coreAPI",
          "endpoint": "https://fvrxi0jfn6.execute-api.us-east-1.amazonaws.com/dev",
          "region": "us-east-1"
      }
  ],
  "aws_cognito_identity_pool_id": "us-east-1:0ea96b12-09cb-40e6-a2ee-2f1abe765041",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_LAUMH130M",
  "aws_user_pools_web_client_id": "2oluj8uv27im4en4r4ekkpd1su",
  "oauth": {},
  "aws_cognito_username_attributes": [
      "EMAIL"
  ],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": [
      "ADDRESS",
      "EMAIL",
      "NAME",
      "PHONE_NUMBER"
  ],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": [
      "SMS"
  ],
  "aws_cognito_password_protection_settings": {
      "passwordPolicyMinLength": 8,
      "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": [
      "EMAIL"
  ]
};


module.exports = awsmobile;
